// <auto-generated />
using System;
using EscolaDeIdiomas.WebApi.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EscolaDeIdiomas.WebApi.Migrations
{
    [DbContext(typeof(EscolaDeIdiomasContext))]
    partial class EscolaDeIdiomasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EscolaDeIdiomas.WebApi.Domains.Aluno", b =>
                {
                    b.Property<Guid>("idAluno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("nomeCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("idAluno");

                    b.HasIndex("cpf")
                        .IsUnique();

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("Alunos", (string)null);
                });

            modelBuilder.Entity("EscolaDeIdiomas.WebApi.Domains.Matricula", b =>
                {
                    b.Property<Guid>("idMatricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("idAluno")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("idTurma")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("idMatricula");

                    b.HasIndex("idAluno");

                    b.HasIndex("idTurma");

                    b.ToTable("Matriculas", (string)null);
                });

            modelBuilder.Entity("EscolaDeIdiomas.WebApi.Domains.Turma", b =>
                {
                    b.Property<Guid>("idTurma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("anoLetivo")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("descricaoTurma")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("numeroTurma")
                        .HasColumnType("INTEGER");

                    b.HasKey("idTurma");

                    b.HasIndex("numeroTurma")
                        .IsUnique();

                    b.ToTable("Turmas", (string)null);
                });

            modelBuilder.Entity("EscolaDeIdiomas.WebApi.Domains.Matricula", b =>
                {
                    b.HasOne("EscolaDeIdiomas.WebApi.Domains.Aluno", "aluno")
                        .WithMany("Matriculas")
                        .HasForeignKey("idAluno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EscolaDeIdiomas.WebApi.Domains.Turma", "turma")
                        .WithMany("Matriculas")
                        .HasForeignKey("idTurma")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("aluno");

                    b.Navigation("turma");
                });

            modelBuilder.Entity("EscolaDeIdiomas.WebApi.Domains.Aluno", b =>
                {
                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("EscolaDeIdiomas.WebApi.Domains.Turma", b =>
                {
                    b.Navigation("Matriculas");
                });
#pragma warning restore 612, 618
        }
    }
}
